version: '2'

services:
  applications:
    image: tianon/true
    volumes:
      - ${APPLICATION}:/var/www
  php-fpm:
    build:
      context: ./laravel-php7-fpm
    expose:
      - "9000"
    volumes_from:
      - applications
    networks:
      - backend
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes_from:
      - applications
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    



  ### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"