version: '2'

services:
  applications:
    image: registry.cn-hangzhou.aliyuncs.com/basic/mirror-true
    volumes:
      - ${APPLICATION}:/var/www
  ############
  # mysql
  ############
  # mysql:
  #   build:
  #     context: ./mysql
  #   expose:
  #     - "3306"
  #   volumes:
  #     - ./storage/mysql:/var/lib/mysql
  #     - ./mysql/conf.d:/etc/mysql/conf.d
  #   networks:
  #     - backend
  ############
  # mysql
  ############
  redis:
    image: redis
    volumes:
      - ./storage/redis:/data
    expose:
      - "6379"
    networks:
      - backend
  ############
  # PHP
  ############
  php-fpm:
    build:
      context: ./laravel-php7-fpm
    expose:
      - "9000"
    depends_on:
      - redis
    volumes_from:
      - applications
    networks:
      - backend
  ############
  # SOCKET SERVER
  ############
  socker-server:
    build:
      context: ./node
    depends_on:
      - php-fpm
    volumes_from:
      - applications
    expose:
      - "8999"
    networks:
      - frontend
      - backend
  ############
  # NGINX
  ############
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes_from:
      - applications
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  ### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"